### ISSUE TITLE
Go backwards to older commit

### ISSUE THREAD

**Issue by iajohns1** [gios-asu/search-api#43]
Ken's commit to my branch really screwed me up (I am currently really scared about making undesired changes and other issues have now left me utterly confused) and I would like to go back to the commit before he touched my stuff. How would I do that? Also how would I then bring any changes to the main develop branch to mine to keep my branch up to date?

**Comment by idmontie** [comment]
Hmmm in what ways did it mess up your branch?

What you might want to do is:
1. Revert back to the commit before Ken's commit (git checkout **hashOfTheCommitGoesHere**)
2. Make a new branch (git checkout -b my-cool-branch-name)
3. Cherry pick your commits from ian-devel (git cherry-pick **hashOfCommit**) Make sure to do these in order! (IE, oldest to newest)
4. In this new branch, git pull origin develop
5. Resolve all merge conflicts
6. Push this new branch to github
7. Make sure it has all of your commits in it
8. Issue a pull request into develop

**Comment by idmontie** [comment]
If that seems too complicated, it is because it is. You wrote to the history after it was pushed to Github, making it really hard to change the history (ie, remove the commit that Ken made).

It would be easier to just resolve this "mess up" and make a new commit to your current branch with the fixes.

Also, it looks like it is passing on TravisCI, so what exactly is the problem?

**Comment by idmontie** [comment]
Also, please close this issue when you figure it out, thanks!

**Comment by kenprice** [comment]
Try doing a `composer dump-autoload` to update autoload. You have new classes in your branch when you pulled my changes. If you have already done this and have issues, post the symptoms here.

**Comment by idmontie** [comment]
:+1: That's most likely the issue
